
# A fancy name for your implementation of Bauta
bauta.application.name: Oracle Sample
bauta.application.title: ${bauta.application.name}
bauta.application.description: Demo of Oracle-based batch automation
bauta.application.version: '@project.version@'
bauta.application.buildTime: '@bautainstancetimestamp@'
bauta.confirmJobOperations: false

bauta.batch.executor:
  maxThreads: 36
  coreThreads: 1
  queueCapacity: 0


# Optionally replace this with build number from build tool
bauta.application.build: 1

# The base home directory. Typically where reports, logs, etc go
bauta.homeDir:
bauta.jobBeansDir: ${bauta.homeDir}/jobs
bauta.scriptDir: ${bauta.homeDir}/scripts
bauta.reportDir: ${bauta.homeDir}/reports
bauta.logDir: ${bauta.homeDir}/logs

# Enables the interactive shell. If you use the web UI, keep this disabled
spring.shell.interactive.enabled: false
vaadin.productionMode: true

# Http session timeout
server.servlet.session.timeout: 60m

# Rebuild command. Typically kills bauta process, fetches latest code, scripts, beans from VCS
# and then starts a fresh process. Can only be executed once
bauta.rebuildServerCommand: ${bauta.homeDir}/bin/rebuild_server.sh
# Refresh command. Typically calls a script that refreshes scripts, input data etc
bauta.refreshServerCommand: ${bauta.homeDir}/bin/refresh_server.sh


bauta.stagingDB.host: mydbhost
bauta.stagingDB.port: 1521
bauta.stagingDB.service: MYSERVICE
bauta.stagingDB.sid:
bauta.stagingDB.nls_length_semantics: BYTE

# Must be provided as a runtime dependency in the POM
bauta.stagingDB.driverClassName: "oracle.jdbc.driver.OracleDriver"
# Comma-separated list of properties that will be used when creating the staging DB datasource
# Useful when connecting using Oracle wallet, e.g.
#  oracle.net.wallet_location=(source=(method=file)(method_data=(directory=/opt/oracle/mywallet)))
# bauta.stagingDB.connectionProperties: "oracle.net.wallet_location=(source=(method=file)(method_data=(directory=/opt/oracle/mywallet)))"
bauta.stagingDB.url: jdbc:oracle:thin:@${bauta.stagingDB.host}:${bauta.stagingDB.port}/${bauta.stagingDB.service}
#bauta.stagingDB.url: jdbc:oracle:thin:@${bauta.stagingDB.host}:${bauta.stagingDB.port}:${bauta.stagingDB.sid}
bauta.stagingDB.sqlplus.connectionIdentifier: ${bauta.stagingDB.username}/${bauta.stagingDB.password}@${bauta.stagingDB.host}:${bauta.stagingDB.port}/${bauta.stagingDB.service}
bauta.stagingDB.sqlplus.adminConnectionIdentifier: ${bauta.stagingDB.adminusername}/${bauta.stagingDB.adminpassword}@${bauta.stagingDB.host}:${bauta.stagingDB.port}/${bauta.stagingDB.service}

---
spring:
  profiles: mattias
bauta:
  homeDir: /home/arbinmat/Projects/oracle_sample_home
  jobBeansDir: /home/arbinmat/Projects/bauta/bauta-sample-oracle/src/main/install/jobs
  scriptDir: /home/arbinmat/Projects/bauta/bauta-sample-oracle/src/main/install/scripts
  application.description: Mattias Demo of Oracle-based batch automation
  rebuildServerCommand: ${bauta.homeDir}/bin/rebuild_command 1 master
  refreshServerCommand: ${bauta.homeDir}/bin/refresh_command 1 master

  stagingDB:
    connectionPool:
      maxTotal: 100
  security:
    enabled: true
    configFilePath: /home/arbinmat/Projects/bauta/bauta-sample-oracle/src/main/install/bauta_security.json

bauta.stagingDB.username: ARBINMAT
bauta.stagingDB.password: ARBINMAT
bauta.stagingDB.adminusername: ARBINMAT
bauta.stagingDB.adminpassword: ARBINMAT

---
spring:
  profiles: mattias-win
vaadin.productionMode: false
bauta:
  homeDir: c:/projects/oracle_sample_home
  jobBeansDir: c:/projects/Bauta/bauta-sample-oracle/src/main/install/jobs
  scriptDir: c:/projects/Bauta/bauta-sample-oracle/src/main/install/scripts
  application.description: Mattias Demo of Oracle-based batch automation
  rebuildServerCommand: ${bauta.homeDir}/bin/rebuild_command 1 master
  stagingDB:
    connectionPool:
      maxTotal: 100

bauta.stagingDB.username: ARBINMAT
bauta.stagingDB.password: ARBINMAT
bauta.stagingDB.adminusername: ARBINMAT
bauta.stagingDB.adminpassword: ARBINMAT

