FROM openjdk:11.0.12-jre-slim
RUN mkdir -p /opt/bauta
COPY target/bauta.zip /opt/bauta/bauta.zip
RUN apt-get update \
    && apt-get upgrade \
    && apt-get install -y unzip \
    && apt-get install -y python3 \
    && apt-get install -y python3-pip
    && apt-get install -y nodejs

RUN unzip -o /opt/bauta/bauta.zip -d /opt/bauta
WORKDIR /opt/bauta/
EXPOSE 8080
ENTRYPOINT ["bash","bin/startBauta.sh", "-h", "/opt/bauta/home"]