# This is a basic workflow that is manually triggered

name: Release Workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.

on: 
  workflow_dispatch:
     inputs:
       releaseVersion: 
         description: Version of the release
         required: true
       developmentVersion: 
         description: Next development version
         required: true


jobs:
  release:

    runs-on: ubuntu-latest
    
    steps:
    - name: checkout project
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Configure git
      run: |
        git config user.email "release-bot@ikama.se"
        git config user.name "release-bot"
        
    - id: install-secret-key
      name: Install gpg secret key
      run: |
        cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
        gpg --list-secret-keys --keyid-format LONG

    - name: Pre-release script
      run: source ./pre_release.sh -v ${{ github.event.inputs.releaseVersion }} -d ${{ github.event.inputs.developmentVersion }}

    - name: Deploy script
      run: source ./release.sh -v ${{ github.event.inputs.releaseVersion }} -d ${{ github.event.inputs.developmentVersion }}
      env:
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSPHRASE }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PGP_PASSPHRASE: ${{secrets.OSSRH_GPG_SECRET_KEY_PASSWORD}}

        
    
   
    - name: Post-release script
      run: source ./post_release.sh -v ${{ github.event.inputs.releaseVersion }} -d ${{ github.event.inputs.developmentVersion }}

